// Single File That You Import
// Windows Enums + EnumSets
pub const OVERLAPPED_WINDOW = @import("windows_enums.zig").OVERLAPPED_WINDOW;
pub const POPUP_WINDOW = @import("windows_enums.zig").POPUP_WINDOW;
pub const TILED_WINDOW = @import("windows_enums.zig").TILED_WINDOW;
pub const Messages = @import("windows_enums.zig").Messages;
pub const SW = @import("windows_enums.zig").SW;
pub const REDRAW = @import("windows_enums.zig").REDRAW;
// Enum Types
pub const ATOM = @import("windows_types.zig").ATOM;
pub const BOOL = @import("windows_types.zig").BOOL;
pub const DWORD = @import("windows_types.zig").DWORD;
pub const HBRUSH = @import("windows_types.zig").HBRUSH;
pub const HCURSOR = @import("windows_types.zig").HCURSOR;
pub const HICON = @import("windows_types.zig").HICON;
pub const HINSTANCE = @import("windows_types.zig").HINSTANCE;
pub const HMENU = @import("windows_types.zig").HMENU;
pub const HWND = @import("windows_types.zig").HWND;
pub const LRESULT = @import("windows_types.zig").LRESULT;
pub const LPARAM = @import("windows_types.zig").LPARAM;
pub const WPARAM = @import("windows_types.zig").WPARAM;
// Fns
pub const CreateWindowA = @import("windows_fns.zig").CreateWindowA;
pub const CreateWindowW = @import("windows_fns.zig").CreateWindowW;
pub const CreateWindowExA = @import("windows_fns.zig").CreateWindowExA;
pub const CreateWindowExW = @import("windows_fns.zig").CreateWindowExW;
pub const DefWindowProcA = @import("windows_fns.zig").DefWindowProcA;
pub const DefWindowProcW = @import("windows_fns.zig").DefWindowProcW;
pub const DestroyWindow = @import("windows_fns.zig").DestroyWindow;
pub const DispatchMessageA = @import("windows_fns.zig").DispatchMessageA;
pub const DispatchMessageW = @import("windows_fns.zig").DispatchMessageW;
pub const GetMessageA = @import("windows_fns.zig").GetMessageA;
pub const GetMessageW = @import("windows_fns.zig").GetMessageW;
pub const GetModuleHandleA = @import("windows_fns.zig").GetModuleHandleA;
pub const GetModuleHandleW = @import("windows_fns.zig").GetModuleHandleW;
pub const GetSysColorBrush = @import("windows_fns.zig").GetSysColorBrush;
pub const LoadCursorA = @import("windows_fns.zig").LoadCursorA;
pub const LoadCursorW = @import("windows_fns.zig").LoadCursorW;
pub const LoadIconA = @import("windows_fns.zig").LoadIconA;
pub const LoadIconW = @import("windows_fns.zig").LoadIconW;
pub const PostQuitMessage = @import("windows_fns.zig").PostQuitMessage;
pub const ShowWindow = @import("windows_fns.zig").ShowWindow;
pub const RegisterClassA = @import("windows_fns.zig").RegisterClassA;
pub const RegisterClassW = @import("windows_fns.zig").RegisterClassW;
pub const RegisterClassExA = @import("windows_fns.zig").RegisterClassExA;
pub const RegisterClassExW = @import("windows_fns.zig").RegisterClassExW;
pub const UpdateWindow = @import("windows_fns.zig").UpdateWindow;
pub const UnregisterClassA = @import("windows_fns.zig").UnregisterClassA;
pub const UnregisterClassW = @import("windows_fns.zig").UnregisterClassW;
pub const WndProcA = @import("windows_fns.zig").WndProcA;
pub const WndProcW = @import("windows_fns.zig").WndProcW;
// Structs
pub const WNDCLASSA = @import("windows_structs.zig").WNDCLASSA;
pub const WNDCLASSW = @import("windows_structs.zig").WNDCLASSW;
pub const WNDCLASSEXA = @import("windows_structs.zig").WNDCLASSEXA;
pub const WNDCLASSEXW = @import("windows_structs.zig").WNDCLASSEXW;
pub const MSG = @import("windows_structs.zig").MSG;
pub const POINT = @import("windows_structs.zig").POINT;
